# Generated by Django 3.1.1 on 2020-10-25 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2020, 10, 25, 9, 56, 54, 583671)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2020, 10, 25, 9, 56, 54, 583175)),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurantApp.ingredienttype'),
        ),
    ]
