# Generated by Django 4.1 on 2022-08-16 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_auto_20201025_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2022, 8, 16, 13, 4, 36, 725630)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2022, 8, 16, 13, 4, 36, 725602)),
        ),
    ]
