# Generated by Django 3.1.1 on 2020-09-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
    ]
