# Generated by Django 3.1.1 on 2020-10-25 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_auto_20201025_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='ingredient_type',
            field=models.CharField(choices=[('ND', 'NOT DEFINED'), ('S', 'Ser'), ('M', 'Mięso'), ('W', 'Warzywo'), ('N', 'Napój')], default='ND', max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2020, 10, 25, 13, 47, 17, 846345)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2020, 10, 25, 13, 47, 17, 846345)),
        ),
    ]
