# Generated by Django 3.1.1 on 2020-09-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_auto_20200914_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
