# Generated by Django 3.1.1 on 2020-10-25 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_auto_20201025_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('ND', 'NOT DEFINED'), ('S', 'Ser'), ('M', 'Mięso'), ('W', 'Warzywo'), ('N', 'Napój')], default='ND', max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2020, 10, 25, 13, 51, 31, 121577)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2020, 10, 25, 13, 51, 31, 121577)),
        ),
        migrations.DeleteModel(
            name='IngredientType',
        ),
    ]
