# Generated by Django 3.1.1 on 2020-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_auto_20200914_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'Kilogramy'), ('DG', 'Dekagramy'), ('GR', 'Gramy'), ('SZT', 'Sztuki')], default='GR', max_length=3),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='quantity_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'Kilogramy'), ('DG', 'Dekagramy'), ('GR', 'Gramy'), ('SZT', 'Sztuki')], max_length=3),
        ),
    ]
