# Generated by Django 3.1.1 on 2020-09-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0006_auto_20200914_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'Kilogramy'), ('DG', 'Dekagramy'), ('GR', 'Gramy'), ('SZT', 'Sztuki')], max_length=3),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='quantity_usage',
            field=models.IntegerField(),
        ),
    ]
